#!/bin/bash
#sed -i "s/\r//" filename
if [ $(id -u) != "0" ]; then
    echo "请以root用户登录以完成安装！"
    exit 1
fi
read -p "请输入tar包所在完整路径：" tarpath
read -p "请输入mongodb安装上级目录目录路径：" mongodbpath
read -p "请输入mongodbtar包完整名（不包含tar）：" mongodbtar


tar -zxvf $tarpath/''$mongodbtar'.tgz'
mv $mongodbtar $mongodbpath/mongodb
mkdir -p $mongodbpath/mongodb/log $mongodbpath/mongodb/data/db
touch $mongodbpath/mongodb/log/mongodb.log $mongodbpath/mongodb/bin/mongodb.conf /lib/systemd/system/mongodb.service

cat >$mongodbpath/mongodb/bin/mongodb.conf<<EOF
dbpath=$mongodbpath/mongodb/data/db
logpath=$mongodbpath/mongodb/log/mongodb.log
logappend=true
journal=true
fork=true
bind_ip=0.0.0.0
EOF

cat >/etc/profile<<EOF
export MONGODB_HOME=$mongodbpath/mongodb
export PATH=$PATH:$MONGODB_HOME/bin
EOF

source /etc/profile

cat >/lib/systemd/system/mongodb.service<<EOF
[Unit]
Description=mongodb
After=network.target remote-fs.target nss-lookup.target
[Service]
Type=forking
ExecStart=/$mongodbpath/mongodb/bin/mongod --config /$mongodbpath/mongodb/bin/mongodb.conf
ExecReload=/bin/kill -s HUP $MAINPID
ExecStop=/$mongodbpath/mongodb/bin/mongod --shutdown --config /$mongodbpath/mongodb/bin/mongodb.conf
PrivateTmp=true 
[Install]
WantedBy=multi-user.target
EOF

systemctl enable mongodb
systemctl start mongodb
systemctl status mongodb

firewall-cmd --zone=public --add-port=27017/tcp --permanent
firewall-cmd --reload
firewall-cmd --permanent --query-port=27017/tcp

