#!/bin/bash
#sed -i "s/\r//" filename
if [ $(id -u) != "0" ]; then
    echo "请以root用户登录以完成安装！"
    exit 1
fi
read -p "请输入tar包所在完整路径：" tarpath
read -p "请输入mongodb安装上级目录目录路径：" mongodbpath
tar -zxvf $tarpath/mongodb-linux-x86_64-4.0.12.tgz
mv mongodb-linux-x86_64-4.0.12 $mongodbpath/mongodb
mkdir -p $mongodbpath/mongodb/log $mongodbpath/mongodb/data/db
touch $mongodbpath/mongodb/log/mongodb.log $mongodbpath/mongodb/bin/mongodb.conf 
echo "dbpath=$mongodbpath/mongodb/data/db">$mongodbpath/mongodb/bin/mongodb.conf
echo "logpath=$mongodbpath/mongodb/log/mongodb.log">>$mongodbpath/mongodb/bin/mongodb.conf
echo "logappend=true">>$mongodbpath/mongodb/bin/mongodb.conf
echo "journal=true">>$mongodbpath/mongodb/bin/mongodb.conf
echo "fork=true">>$mongodbpath/mongodb/bin/mongodb.conf
echo "bind_ip=0.0.0.0">>$mongodbpath/mongodb/bin/mongodb.conf
echo "auth=false">>$mongodbpath/mongodb/bin/mongodb.conf
echo "export MONGODB_HOME=$mongodbpath/mongodb">>/etc/profile
echo "export PATH=$PATH:$MONGODB_HOME/bin">>/etc/profile
source /etc/profile
$mongodbpath/mongodb/bin/mongod --config $mongodbpath/mongodb/bin/mongodb.conf




